[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Erweiterte Secrets-Scanning-Ausschlüsse
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**,*.md,README.md,MIGRATION_STATUS_CURRENT.md,windsurf_deployment.yaml,node_modules/**"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_PROJECT_ID,NEXT_PUBLIC_SUPABASE_URL,NEXTAUTH_URL,NEXT_PUBLIC_BASE_URL"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and SPA routing
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Next.js API Routes handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Next.js App Router routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 404 handling
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
